FROM node:20-alpine AS frontend
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM golang:1.24-alpine AS backend
WORKDIR /app
COPY go.mod ./
# Copy source FIRST so tidy can scan imports
COPY . .
RUN go mod tidy
# Copy frontend dist separately as it's generated by the previous stage
COPY --from=frontend /app/dist/ internal/static/web/
RUN CGO_ENABLED=0 go build -o server ./cmd/server

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=backend /app/server .
EXPOSE 8181
CMD ["./server"]
